# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banners',
            table='banners',
        ),
    ]
