# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggs', '0002_auto_20180815_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_title', models.CharField(max_length=50)),
                ('Article_images', models.CharField(max_length=50)),
                ('Article_content', models.TextField(null=True)),
                ('Article_author', models.CharField(max_length=30)),
                ('Article_classify', models.CharField(max_length=20)),
                ('Article_time', models.TimeField(auto_now=True)),
                ('Article_readNum', models.IntegerField()),
                ('Article_likeNum', models.IntegerField()),
            ],
            options={
                'db_table': 'Article',
            },
        ),
    ]
