# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-18 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloggs', '0004_classify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Article_classify',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bloggs.Classify'),
        ),
    ]
