# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-18 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggs', '0005_auto_20180818_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Article_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
