# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggs', '0007_auto_20180818_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Newpaper_title', models.CharField(max_length=100)),
                ('Newpaper_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Newpaper',
            },
        ),
    ]
