# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggs', '0008_newpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpaper',
            name='Newpaper_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
