# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggs', '0011_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_tilte', models.CharField(max_length=50)),
                ('Time_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TimeLife',
            },
        ),
    ]
