# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggs', '0012_timelife'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Article_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
