# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggs', '0013_auto_20180830_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='heardyou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
                ('banner_url', models.CharField(max_length=50)),
            ],
        ),
    ]
