# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggs', '0014_heardyou'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='heardyou',
            table='heardyou',
        ),
    ]
